# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatGPTCompatibilitytestOSGoogleChromeDesktop():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatGPTCompatibilitytestOSGoogleChromeDesktop(self):
    # Test name: Chat_GPT_Compatibility_test_OS_GoogleChrome_Desktop
    # Step # | name | target | value
    # 1 | open | https://chat.openai.com/ | 
    self.driver.get("https://chat.openai.com/")
    # 2 | setWindowSize | 1280x775 | 
    self.driver.set_window_size(1280, 775)
    # 3 | click | css=.md\3Amax-w-2xl | 
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Amax-w-2xl").click()
    # 4 | click | css=.hover\3A bg-gray-200:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-200:nth-child(1)").click()
    # 5 | click | css=.hover\3A bg-gray-200:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-200:nth-child(1)").click()
    # 6 | click | css=.flex:nth-child(2) > .flex:nth-child(2) > .w-full:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex:nth-child(2) > .w-full:nth-child(1)").click()
    # 7 | click | css=.hover\3A bg-gray-200:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-200:nth-child(2)").click()
    # 8 | click | css=.m-1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".m-1").click()
    # 9 | mouseOver | css=.m-1 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".m-1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | click | css=.btn-neutral > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-neutral > .flex").click()
  
