# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatGPTCompatibilitytestOSFirefox():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatGPTCompatibilitytestOSFirefox(self):
    # Test name: ChatGPT_Compatibility_test_OS_Firefox
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://chat.openai.com/")
    # 2 | setWindowSize | 1205x691 | 
    self.driver.set_window_size(1205, 691)
    # 3 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 4 | click | css=.hover\3A bg-gray-200:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-200:nth-child(1)").click()
    # 5 | click | css=.m-1 > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".m-1 > path").click()
    # 6 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | linkText=New chat | 
    self.driver.find_element(By.LINK_TEXT, "New chat").click()
    # 10 | click | css=.hover\3A bg-gray-200:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-200:nth-child(3)").click()
    # 11 | click | css=.md\3A bottom-3 | 
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3A bottom-3").click()
    # 12 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 14 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 15 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 16 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 17 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 18 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 19 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 20 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
